// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user_settings.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	"backend/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockUserSettingsRepository is a mock of UserSettingsRepository interface.
type MockUserSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsRepositoryMockRecorder
}

// MockUserSettingsRepositoryMockRecorder is the mock recorder for MockUserSettingsRepository.
type MockUserSettingsRepositoryMockRecorder struct {
	mock *MockUserSettingsRepository
}

// NewMockUserSettingsRepository creates a new mock instance.
func NewMockUserSettingsRepository(ctrl *gomock.Controller) *MockUserSettingsRepository {
	mock := &MockUserSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockUserSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsRepository) EXPECT() *MockUserSettingsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserSettingsRepository) Create(ctx context.Context, userSettings *model.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userSettings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserSettingsRepositoryMockRecorder) Create(ctx, userSettings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserSettingsRepository)(nil).Create), ctx, userSettings)
}

// GetByID mocks base method.
func (m *MockUserSettingsRepository) GetByID(ctx context.Context, userId string) (*model.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userId)
	ret0, _ := ret[0].(*model.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserSettingsRepositoryMockRecorder) GetByID(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserSettingsRepository)(nil).GetByID), ctx, userId)
}

// Update mocks base method.
func (m *MockUserSettingsRepository) Update(ctx context.Context, userSettings *model.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userSettings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserSettingsRepositoryMockRecorder) Update(ctx, userSettings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserSettingsRepository)(nil).Update), ctx, userSettings)
}
