// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handler"
	"backend/internal/job"
	"backend/internal/repository"
	"backend/internal/router"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/app"
	"backend/pkg/jwt"
	"backend/pkg/log"
	"backend/pkg/server/http"
	"backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userSettingsRepository := repository.NewUserSettingsRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository, userSettingsRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	recordRespository := repository.NewRecordRepository(repositoryRepository)
	recordService := service.NewRecordService(serviceService, recordRespository)
	recordHandler := handler.NewRecordHandler(handlerHandler, recordService)
	reportRepository := repository.NewReportRepository(repositoryRepository)
	reportService := service.NewReportService(serviceService, reportRepository, recordService, userSettingsRepository)
	reportHandler := handler.NewReportHandler(handlerHandler, reportService)
	dashboardService := service.NewDashboardService(serviceService, recordRespository, reportRepository)
	dashboardHandler := handler.NewDashboardHandler(handlerHandler, dashboardService)
	routerDeps := router.RouterDeps{
		Logger:           logger,
		Config:           viperViper,
		JWT:              jwtJWT,
		UserHandler:      userHandler,
		RecordHandler:    recordHandler,
		ReportHandler:    reportHandler,
		DashboardHandler: dashboardHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewUserSettingsRepository, repository.NewRecordRepository, repository.NewReportRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRecordService, service.NewReportService, service.NewDashboardService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRecordHandler, handler.NewReportHandler, handler.NewDashboardHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("server"))
}
