export const NAV_LABELS = {
  brand: 'Thinking-Calendar',
  today: '今天',
  attendance: '补卡',
  history: '历史',
  dashboard: '看板',
  reports: '报告',
  settings: '设置',
  recent: '最近报告',
  viewAll: '查看全部 →',
  themeDark: '暗黑模式',
  themeLight: '亮色模式',
  openMenu: '打开菜单',
  closeMenu: '关闭菜单'
}

export const PAGE_TEXT = {
  loginTitle: 'Thinking-Calendar',
  loginSubtitle: '专注工作记录，AI 帮你写总结',
  loginButton: '登录/注册',
  loginHelp: '首次使用将自动注册账号',
  showPassword: '显示密码',
  hidePassword: '隐藏密码',
  loginSuccess: '登录成功',
  loginFail: '登录失败，请稍后重试',
  loginRequired: '请填写用户名和密码',
  loginUsernameLength: '用户名长度需 6-20 个字符',
  loginPasswordLength: '密码长度需 6-32 个字符',
  loginAuthRequired: '请先登录后再访问',
  usernamePlaceholder: '请输入用户名',
  passwordPlaceholder: '请输入密码',
  futureDateForbidden: '不能编辑未来日期的日志',
  reportFutureDateForbidden: '不能选择未来日期生成报告',
  todayTitle: '今天',
  historyTitle: '历史记录',
  dashboardTitle: '记录看板',
  previousMonth: '上个月',
  nextMonth: '下个月',
  reportsTitle: '报告中心',
  editorPlaceholder: '记录今天的重点、产出、问题与下一步计划...',
  emptyLog: '暂无记录，开始书写吧',
  statisticsPrefix: '本月已记录',
  statisticsGap: '未记录',
  statisticsRate: '记录率',
  reportTypeLabel: '报告类型',
  templateLabel: '版式',
  timeRangeLabel: '时间范围',
  reportWeekLabel: '周报',
  reportMonthLabel: '月报',
  reportYearLabel: '年报',
  selectReportHint: '选择一条报告查看详情',
  confirmReport: '确认报告',
  copyReport: '复制',
  exportReport: '导出 PDF',
  exportBatch: '批量导出 PDF',
  exportSelectAll: '全选',
  exportDeselectAll: '取消全选',
  exportCancel: '取消',
  exportSelected: '导出选中',
  generateNow: '立即生成',
  generateYearly: '生成年终总结',
  weeklyReport: '周报',
  monthlyReport: '月报',
  yearlyReport: '年报',
  confirmed: '已确认',
  unconfirmed: '未确认',
  noReport: '暂无报告',
  noLog: '暂无日志',
  loading: '加载中…',
  loadFail: '加载失败',
  save: '保存',
  deleteRecord: '删除记录',
  confirmDeleteTitle: '确认删除记录',
  confirmDeleteHint: '删除后，该日期的记录将不再用于生成报告。',
  confirmDeleteAction: '确认删除',
  generating: '生成中…',
  autoSaveStatus: {
    saved: '已保存',
    pending: '等待自动保存',
    saving: '保存中…',
    error: '保存失败',
    empty: '内容已清空，请手动删除记录'
  },
  retrySave: '重试',
  saveSuccess: '保存成功',
  saveFail: '保存失败',
  generateSuccess: '生成成功',
  generateFail: '生成失败',
  generateAgain: '重新生成',
  confirmSuccess: '确认成功',
  confirmFail: '确认失败',
  copySuccess: '已复制到剪贴板',
  copyFail: '复制失败',
  exportSuccess: '导出完成',
  exportFail: '导出失败',
  reportGeneratingHint: 'AI 正在生成，稍候即会出现内容',
  viewInDialog: '在弹窗中编辑',
  recordsCount: '条记录',
  lastUpdated: '更新',
  lastUpdatedRecent: '最近更新',
  recordedTag: '已记录',
  todayWeekPrefix: '第',
  todayWeekSuffix: '周',
  todayGenerateAction: '生成本周报告 →',
  searchDate: '选择日期',
  searchRecords: '搜索日期或记录内容',
  noSearchResults: '没有找到匹配的记录',
  exportRecords: '导出记录 Markdown',
  exportMarkdown: '导出 Markdown',
  reportFilterLabel: '报告状态',
  reportFilterAll: '全部',
  reportFilterPending: '待确认',
  reportFilterConfirmed: '已确认',
  reportFilterGenerating: '生成中',
  reportFilterFailed: '失败',
  reportMaterialTitle: '生成材料',
  reportMaterialCount: '已有记录',
  reportMaterialMissing: '待补记录',
  reportMaterialYear: '已确认的周报和月报',
  reportMaterialReady: '材料已齐备',
  regenerateWarning: '重新生成成功后将覆盖当前报告内容，继续吗？',
  reportDraftSaved: '草稿已自动保存',
  reportFailed: '生成失败',
  reportProcessing: '生成中',
  sourceDateLabel: '查看并补写',
  regenerateConfirm: '继续重新生成',
  missingFill: '点击补充',
  yearlyHint: '基于已确认的周报或月报生成',
  userMenuGuest: '未登录',
  userMenuLogout: '退出登录',
  settingsTitle: '设置',
  settingsSubtitle: '配置周报、月报生成模板',
  settingsWeekTitle: '周报模板',
  settingsMonthTitle: '月报模板',
  settingsTemplateHint: '模板将用于生成报告时替换默认提示词',
  settingsEmpty: '暂无模板，点击编辑',
  settingsEdit: '编辑模板',
  settingsSave: '保存模板',
  settingsLoadFail: '加载设置失败',
  settingsSaveFail: '保存设置失败',
  refineToggle: 'AI 优化',
  refineToggleCollapse: '收起反馈',
  refinePlaceholder: '输入优化建议，如"精简到300字"、"补充更多细节"、"第三条关于风险的表述有问题"...',
  refineReport: '发送反馈优化',
  refining: '优化中…',
  refineSuccess: '优化成功',
  refineFail: '优化失败'
}

export const ATTENDANCE_TEXT = {
  pageTitle: '补卡',
  pageSubtitle: '记录与推送设置',
  sectionTitle: '补卡记录',
  sectionSubtitle: '本月补卡次数与记录',
  usageLabel: '本月已用',
  limitLabel: '上限',
  countUnit: '次',
  statusLocked: '已锁定',
  statusOpen: '未推送',
  lockedHint: '本月已推送，记录不可修改',
  openHint: '推送前可修改记录',
  addTitle: '新增补卡记录',
  dateLabel: '补卡日期',
  datePlaceholder: '选择日期',
  dateRequired: '请先选择补卡日期',
  typeLabel: '打卡类型',
  typePlaceholder: '选择类型',
  noteLabel: '备注',
  notePlaceholder: '可选，便于后续回忆',
  noteEmpty: '无备注',
  addButton: '新增记录',
  listHeaderDate: '日期',
  listHeaderType: '类型',
  listHeaderNote: '备注',
  listHeaderAction: '操作',
  actionDelete: '删除',
  emptyRecords: '暂无补卡记录',
  limitReached: '已达到本月补卡上限',
  crossMonthForbidden: '仅允许选择当月日期',
  futureDateForbidden: '当月未来日期不可补卡',
  lockedActionForbidden: '本月已推送，记录已锁定',
  typeIn: '上班',
  typeOut: '下班',
  scheduleTitle: '推送计划',
  scheduleSubtitle: '按设置时间自动发送补卡清单邮件',
  settingsTitle: '补卡设置',
  settingsSubtitle: '配置补卡次数与邮件推送',
  limitSettingLabel: '每月补卡上限',
  limitPlaceholder: '请输入上限次数',
  pushDayLabel: '推送日期',
  pushTimeLabel: '推送时间',
  pushRangeLabel: '汇总范围',
  pushEmailLabel: '收件邮箱',
  emailUnset: '未设置',
  rangeCurrent: '当月',
  lastDayLabel: '最后一天',
  daySuffix: '号',
  emailPlaceholder: '请输入收件邮箱',
  saveSettings: '保存设置',
  editSettings: '编辑设置',
  settingsSavedHint: '已保存',
  emailRequired: '请先填写收件邮箱',
  settingsHint: '推送后自动锁定当月记录',
  loadFail: '补卡信息加载失败',
  settingsSaveSuccess: '补卡设置已保存',
  settingsSaveFail: '补卡设置保存失败',
  recordSaveSuccess: '补卡记录已保存',
  recordSaveFail: '补卡记录保存失败',
  recordDeleteSuccess: '补卡记录已删除',
  recordDeleteFail: '补卡记录删除失败',
  historyTitle: '历史补卡记录',
  historySubtitle: '按月份查看补卡明细与推送状态',
  historyEmpty: '暂无历史补卡记录',
  monthLabel: '月份',
  monthUsageLabel: '补卡次数',
  monthStatusLabel: '推送状态',
  pushSendAtLabel: '计划发送',
  pushSentAtLabel: '实际发送',
  pushErrorLabel: '失败原因',
  pushActionLabel: '手动推送',
  pushNowButton: '手动推送',
  pushConfirmTitle: '确认推送',
  pushConfirmMonth: '推送月份',
  pushConfirmCount: '记录条数',
  pushConfirmEmail: '收件邮箱',
  pushConfirmAction: '确认发送',
  pushingButton: '推送中…',
  pushManualSuccess: '已触发手动推送',
  pushManualFail: '手动推送失败',
  pushStatusNotPushed: '未推送',
  pushStatusPending: '推送中',
  pushStatusSent: '已成功',
  pushStatusFailed: '推送失败',
  pushTimeEmpty: '暂无',
  monthRecordsLabel: '当月记录',
  sampleNote: '外出会议'
}

export const ATTENDANCE_OPTIONS = {
  types: [
    { value: 'in', label: '上班' },
    { value: 'out', label: '下班' }
  ],
  ranges: [{ value: 'current', label: '当月' }]
}

export const REPORT_OPTIONS = {
  period: [
    { value: 'week', label: '周报' },
    { value: 'month', label: '月报' },
    { value: 'year', label: '年报' }
  ],
  template: [
    { value: 'formal', label: '正式版' },
    { value: 'simple', label: '简约版' }
  ]
}

export const REPORT_FILTER_OPTIONS = [
  { value: 'all', label: PAGE_TEXT.reportFilterAll },
  { value: 'pending', label: PAGE_TEXT.reportFilterPending },
  { value: 'confirmed', label: PAGE_TEXT.reportFilterConfirmed },
  { value: 'generating', label: PAGE_TEXT.reportFilterGenerating },
  { value: 'failed', label: PAGE_TEXT.reportFilterFailed }
]

export const TOOLBAR_TEXT = {
  bold: '加粗',
  italic: '斜体',
  bullet: '无序列表',
  ordered: '有序列表',
  h2: '二级标题',
  h3: '三级标题'
}

export const DIALOG_TEXT = {
  editLog: '编辑',
  edit: '编辑',
  close: '关闭'
}

export const METADATA_TEXT = {
  title: 'Thinking-Calendar',
  description: '专注工作记录与报告生成的极简工具'
}
